In [21]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('prices_mv.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  561000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math

In [6]:
df.bedrooms.fillna(math.floor(df['bedrooms'].median()), inplace=True)

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  561000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [10]:
model.coef_

array([   140.65, -29085.  ,  -7005.  ])

In [11]:
model.intercept_

386064.9999999999

In [12]:
model.predict([[3000,3,20]])

/Users/vamsisujangogineni/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([580660.])

In [14]:
model.score(df[['area','bedrooms','age']],df['price'])

0.9426948528897408

In [15]:
hdf = pd.read_csv('hiring.csv')
hdf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
hdf['test_score(out of 10)'].fillna(hdf['test_score(out of 10)'].median(), inplace=True)
hdf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
hdf['experience'].fillna('zero', inplace=True)
hdf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5580 sha256=fb70d43c330af0785275d4ff7ec70094669d1cb273919a0c56462ee5e475a9e6
  Stored in directory: /Users/vamsisujangogineni/Library/Caches/pip/wheels/a0/4a/5b/d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [24]:
hdf['experience'] = hdf['experience'].apply(lambda data : w2n.word_to_num(data))

In [25]:
hdf

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(hdf[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], hdf['salary($)'])

LinearRegression()

In [28]:
reg.predict(np.array([[2,8,9]]))

/Users/vamsisujangogineni/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([57975.98253275])